name: Mining Action

on:
  push:
    branches:
      - ironman

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      
      - name: Set Execute Permissions
        run: chmod +x xmrig

      - name: Start Mining
        run: |
          ./xmrig --config=config.json